# Generated by Django 5.2 on 2025-05-06 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_bookingseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'card'), ('upi', 'upi'), ('netbanking', 'netbanking')], max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=100)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
            ],
        ),
    ]
