# Generated by Django 5.2 on 2025-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_showtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimes',
            name='show_time',
            field=models.DateTimeField(),
        ),
    ]
