# Generated by Django 5.2 on 2025-04-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_alter_showtimes_show_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField(blank=True, null=True)),
                ('row_label', models.CharField(max_length=255)),
                ('seat_number', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('VIP', 'VIP'), ('Gold', 'Gold'), ('Regular', 'Regular')], max_length=255)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
    ]
