# Generated by Django 5.2 on 2025-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
