# Generated by Django 5.2 on 2025-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('cast', models.CharField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('trailer_url', models.CharField(blank=True, max_length=20000, null=True)),
                ('status', models.CharField()),
            ],
        ),
    ]
