# Generated by Django 5.2 on 2025-04-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Fantasy', 'Fantasy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Malayalam', 'Malayalam')], max_length=255),
        ),
    ]
