# Generated by Django 5.2 on 2025-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
