# Generated by Django 5.2 on 2025-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movies_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
